### ISSUE TITLE
Don't restore launch metadata when `--clear-cache`

### ISSUE THREAD

**Issue by sclevine** [buildpack/pack#101]

**Comment by ekcasey** [comment]
### Motivation:
Right now `--clear-cache` prevents cached layers from being restored. However metadata from the previous image is still provided by the `analyzer`. This metadata can affect the behavior of the buildpack and result in layers from previous builds being reused rather than rebuilt. Users want to use `--clear-cache` to achieve a truly clean state. Therefore builds run with `--clear-cache` should skip the `analyzer` step.

### Acceptance Criteria:
**Given** I have already built a given image tag once
**When** I run `pack build` with the `--clear-cache` flag
**Then** in addition to deleting any existing cache image, `pack` skips the `restorer` and `analyzer` lifecycle phases

**Comment by mgibson1121** [comment]
This story passes acceptance
