### ISSUE TITLE
Misleading error message when creating builder with missing run or build images

### ISSUE THREAD

**Issue by djoyahoy** [buildpack/pack#119]
When I attempt to create a builder where the run-image or the build-image do not exist, I get an error message telling me that my builder image does not exist. This obviously does not make sense.

**Comment by mgibson1121** [comment]
@djoyahoy This looks good, wanted to check one use case though.  If both the builder and the run image are missing, the error message only alerts the user of the first image that is missing, not both.  Would it be difficult/complicated to tell the user when both are missing?

**Comment by ekcasey** [comment]
@mgibson1121 did you mean "build image" instead of "builder" in your comment? It's okay if the builder doesn't exist yet.

Also, I am realizing that this issue referencing checking for the run image which I'm pretty sure we still don't do. Not sure how we want to handle that. You don't actually need the run image to exist to create a builder image. But it might be nice to check anyways?

**Comment by djoyahoy** [comment]
@ekcasey I mentioned run-image in the original comment by mistake. I agree that you don't need the run image to create a builder image. I'm happy to do that in another issue or ignore it for now.

**Comment by mgibson1121** [comment]
@ekcasey Yes, I was referring to the builder image rather than the builder.  But based on my testing, your comment about not checking for the run-image isn't correct.  Given the attached builder 
![Screen Shot 2019-04-10 at 3 55 03 PM](https://user-images.githubusercontent.com/18624859/55909057-07349d00-5ba9-11e9-89d0-c0ee147ed8eb.png).  If I try `pack create-builder buildingbuilder/acceptance:ci -b builder.toml --publish`, then I see `ERROR: failed to decode builder config from file builder.toml: Near line 21 (last key parsed 'stack.run-image'): expected value but found '\n' instead`.  So it seems that we are checking for the run image.

**Comment by djoyahoy** [comment]
@mgibson1121 that is a `toml` parse error that is not specific to pack. Try creating the builder with `run-image = ""` in the builder.toml.

**Comment by mgibson1121** [comment]
Upon further testing w/ @djoyahoy.  The current functionality in pack version darwin 94 is that pack throws an error when trying to create a builder when **either** the run image or build image fields are left blank.  Seems to us that a builder without both makes no sense, so we should probably throw an error when either one is missing or invalid within the builder.toml.  @ekcasey I think we should reject this story because it doesn't reflect the product outcome outlined in my comment.  Thoughts?

**Comment by mgibson1121** [comment]
Separate comment:  do we do any validation on whether or not the build/run images are valid?  That seems much more valuable than throwing an error if the run/build image fields contain an empty string.  My current understanding of the scope of this story is that the errors will only trigger if the user explicitly types `""` in the build image or run image fields.  Seems pretty unlikely the user would do that.  My assumption is that it's more likely that the user would either enter an invalid build/run image or leave the field blank (and trigger the toml error I link to above).

**Comment by mgibson1121** [comment]
I think it's smart from a UX perspective for validation to be performed on both the run/build images for:

1) Whether or not the specified image is a blank string (covered here)
2) Whether or not the specified image is available on the docker daemon when the user runs w/o --publish flag
3) Whether or not the specified image is available on the docker daemon when the user runs w/ --publish flag

Captured this functionality for the run-image in #155 and accepting this story.

**Comment by ekcasey** [comment]
fixed on `master`, will ship in `0.2.0`
