### ISSUE TITLE
`pack create` allows a developer to create a detect image in order to run their custom buildpack

### ISSUE THREAD

**Issue by ssisil** [buildpack/pack#16]
__GIVEN__ I have a 1 to many V3 buildpacks in a <buildpacks dir> that has the following structure :
```
buildpacks dir
|__io.buildpacks.nodejs
    |__v1.0.0
    |__v1.0.1
    |__latest -> v1.0.1 
|__io.buildpacks.java
    |__v2.0.5
    |__latest -> v2.0.5
|__order.toml

```
__AND__  order.toml provides buildpack groups, build and run image names
__WHEN__ I run `pack create  <detect image> --path <buildpacks dir> --base-image <base image>`
__THEN__ detect image will be created 
__AND__ all the build and run images will be created
__AND__ the following will be displayed to the user
```
Image: example.com/myorg/repo@434a7be...

Tip: Run `pack build <image name> --detect-image <detect image> --path <app source code>` to use this buildpack
```
__Note__
- Determine if latest dir can be an actual folder or needs to be a symlink to a specific version
ANSWER: must be symlink
- Add `--publish` flag to support publishing image to remote registry

**Defaults**
- --path = `.`
- --base-image = `packs/v3`

**Comment by dgodd** [comment]
RE: Determine if latest dir can be an actual folder or needs to be a symlink to a specific version

Currently the folder structure is what determines the name/version pairs which can be used during `build`. So symlinks are fine, they just add extra options.

This leads to a validation which `create` should probably perform; check that the name/version in the buildpack.toml file exists on the disk structure. Thus if `io.buildpacks.nodejs/v2.0.5/buildpack.toml` listed version as `v2.0.5` or `latest` then validation would pass. However if the toml file listed the version as `2.0.5` then validation would not pass (since build would then fail anyway)

**Comment by dgodd** [comment]
RE: remove wget from run image

Currently the run image is based off `packs/v3:latest` which has wget etc....
Also if we removed wget, should we remove ca-certificates? I think that will be annoying at run time

**Comment by sclevine** [comment]
1) Determined that `latest` must be a symlink, otherwise the `builder` fails to find the copy of the buildpack on the filesystem, as the group output by the `detector` has the version path resolved to the value in buildpack.toml.
2) Those comments just meant that we should move everything into the base image so that sample buildpacks can be used with `pack create`. I already did this, and just updated the story to reflect.

**Comment by ssisil** [comment]
@sclevine + @dgodd - sync up on this to make sure the both of you are aligned

**Comment by dgodd** [comment]
@ssisil Currently before running "pack create" it is necessary to have the base-image locally.

https://github.com/buildpack/pack/issues/22 fixes this

**Comment by dgodd** [comment]
@ssisil Is this still relevant?

**Comment by ssisil** [comment]
No - I can delete
