### ISSUE TITLE
Unable to go get 

### ISSUE THREAD

**Issue by micahyoung** [buildpack/pack#48]
**Expected behavior:**
I can use `go get github.com/buildpack/pack` to fetch source

**Observed behavior:**
Failure when running, apparently due to mismatched imported, vendored deps
```
$ docker run -it golang:1.11.1
root@2b66f88f9793:/go# go get github.com/buildpack/pack
# github.com/buildpack/pack/image
src/github.com/buildpack/pack/image/image.go:28:2: cannot use origImage (type "github.com/buildpack/lifecycle/vendor/github.com/google/go-containerregistry/pkg/v1".Image) as type "github.com/google/go-containerregistry/pkg/v1".Image in return argument:
        "github.com/buildpack/lifecycle/vendor/github.com/google/go-containerregistry/pkg/v1".Image does not implement "github.com/google/go-containerregistry/pkg/v1".Image (wrong type for BlobSet method)
                have BlobSet() (map["github.com/buildpack/lifecycle/vendor/github.com/google/go-containerregistry/pkg/v1".Hash]struct {}, error)
                want BlobSet() (map["github.com/google/go-containerregistry/pkg/v1".Hash]struct {}, error)
```

**Comment by sclevine** [comment]
This project requires [Go Modules](https://github.com/golang/go/wiki/Modules) which can be enabled with `GO111MODULE=on`. However, this will not make `go get` work like you describe (see [here](https://github.com/golang/go/wiki/Modules#why-does-installing-a-tool-via-go-get-fail-with-error-cannot-find-main-module)). Instead of using `go get`, clone the repo and run `go build .`.

**Comment by micahyoung** [comment]
Thanks @sclevine. I realize I should have peeked at the travis.yml too. I was able to get it cross-compiled and now looking forward to trying it out on Windows.

**Comment by nebhale** [comment]
Not that this would have been helped by the request in #45.
