### ISSUE TITLE
Enumerating the stacks that a buildpack runs on seems dumb

### ISSUE THREAD

**Issue by dsyer** [buildpack/pack#58]
Maybe this is all part of some plan, but isn't it kind of dumb to have to enumerate all the stacks that a buildpack can run on in `buildpack.toml`? What if there's a new stack which is epsilon different from bionic? Shouldn't my buildpack be able to run on that?

**Comment by josegonzalez** [comment]
A buildpack should probably be vetted against the stack you are attempting to run it on. For instance, its possible that I create a buildpack that can be run against an Alpine Linux stack, but would not be able to run on an Ubuntu Bionic stack. In those cases, the Bionic stack would probably be considered an invalid configuration, and rather than increase support headaches, being able to unequivocally state compatibility is useful. 

Just my two cents :)

**Comment by jchesterpivotal** [comment]
>  What if there's a new stack which is epsilon different from bionic? Shouldn't my buildpack be able to run on that?

Maybe, maybe not. There's no way for us to tell, short of being able to accurately forecast whether buildpack A will work on stack B as well as stack B+epsilon. That smells like the halting problem to me. More loosely it means providing heuristics which would misfire periodically and cause surprise and distress.

I think a better way to look at this is not that it's "a list of things the buildpack can run on", because as you point out, that's not strictly true. Instead it's "a list of things the buildpack author asserts they have checked", which might not be strictly true either, but perhaps less confusing as to scope.

**Comment by sclevine** [comment]
Nothing prevents you from modifying the bionic run and build images and labeling them with `io.buildpacks.stacks.bionic`. This is how I imagine individual platform operators would make extra packages available to developers.

We should probably introduce another label for modified stacks though. That way we can validate that the correct run image is always used for rebase operations.

**Comment by nebhale** [comment]
I view this as a way to indicate that a buildpack has been tested to work on a specified stack.  Given how reliant buildpacks are on the underlying stack below them, I lean towards being very conservative and certifying that a buildpack works on a given stack.  If we find that that can be loosened in the future, and that field can be used to generate warnings rather than outright enforcement errors, that might be a path, but I don't think we're that flexible today.

**Comment by sclevine** [comment]
https://github.com/buildpack/spec/pull/18

**Comment by sclevine** [comment]
Closing as mixins is merged into the spec.
