### ISSUE TITLE
Out of memory errors

### ISSUE THREAD

**Issue by dsyer** [buildpack/pack#63]
Getting this with latest CLI:

```
$ pack-365-linux create-builder dsyer/builder -b builder.toml --no-pull
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x958008, 0x16)
    /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/panic.go:608 +0x72
```

Not really sure what it means. If it means that `pack` is unusable with less than 32GB RAM then I think that's a bug (I have 8 and it's fine for everything else I do on this laptop).

**Comment by nebhale** [comment]
Yeah, that honestly seems like a bug...

**Comment by ekcasey** [comment]
@dsyer The current implementation of `create-builder` is inefficient when it is run against a daemon. It is slow and essentially loads the entire image into memory. We will be fixing it when we play this issue https://github.com/buildpack/roadmap/issues/17. `rebase` has a similar problem https://github.com/buildpack/roadmap/issues/18. These issues are near the top of our backlog.

This is due to the way that the `go-containerregistry` library behaves when operating against a docker daemon (as opposed to a registry). We will be swapping out calls to `go-containerregistry` with our own implementation in the local case (as we have already done with `pack build`).

**Comment by nebhale** [comment]
Any thought of improving `go-containerregistry` and submitting back upstream?

**Comment by ekcasey** [comment]
@dsyer We made performance improvements to the daemon implementation of `create-builder` in `pack`@`v0.0.6`. This problem should be fixed.

Feel free to reopen if you are still seeing suspiciously high memory usage in newer `pack` versions.
