### ISSUE TITLE
Error: could not parse reference

### ISSUE THREAD

**Issue by timfpark** [buildpack/pack#64]
I tried to use pack (for the first time) to build an image for a Node.js application with the following and am getting a cryptic error message:

```
$ pack build tpark.azurecr.io/tpark/testService:latest --path testService
Error: could not parse reference
Usage:
  pack build <image-name> [flags]

Flags:
      --builder string     builder (default "packs/samples")
  -h, --help               help for build
      --no-pull            don't pull images before use
  -p, --path string        path to app dir (default "/Users/timothypark/dev/rhom/ops2/services/locationService")
      --publish            publish to registry
      --run-image string   run image

```

This happens with both 0.0.4 and 0.0.5 - is this user error or a bug?

**Comment by dgodd** [comment]
@timfpark The problem turns out to be due to the library we use to parse registry names not accepting `tpark.azurecr.io/tpark/testService:latest` (it does accept `tpark.azurecr.io/tpark:latest`). I am assuming that the image name you gave us is correct and that the error is in https://github.com/google/go-containerregistry

I will try to get an account with azure and submit a PR to go-containerregistry if necessary. (Or if you feel inspired to do the PR)

**Comment by dgodd** [comment]
So on closer inspection @timfpark I believe that the problem is capitalization. The docker daemon does not allow capitalization and https://github.com/google/go-containerregistry is also enforcing that. If you change to all lower case then all should be good.

**Comment by timfpark** [comment]
Ah - I didn't know that - I'll adjust accordingly.  Thanks for your help!
