### ISSUE TITLE
Update stack docs are wrong

### ISSUE THREAD

**Issue by poy** [buildpack/pack#95]
Looking at the managing stacks doc, it suggests to update a stack do the following:

```
$ pack add-stack org.example.my-stack --build-image my-stack/build:v2 --run-image my-stack/run:v2
```

This yields the following error:
```
ERROR: stack org.example.my-stack already exists
```

**Comment by ekcasey** [comment]
Since we removed the `pack add-stack` command, I am going to close this issue.

Stacks should be easier to work with in pack `v0.1.0`. When doing `pack create-builder` stack images are explicitly set in the `builder.toml`. 

The only other time users might want to think about stacks is when provide copies of a run-image on different registries to improve the performance of `pack build` and `pack rebase`. This can now be done with `pack set-run-image-mirrors`.
